FROM debian:buster

RUN apt-get update && apt-get install -y 	\
		vim				\
		nginx				\
		openssl

COPY ./script.sh ./tmp
COPY ./config/default ./tmp
RUN chmod +x ./tmp/script.sh
CMD [ "./tmp/script.sh" ]
