version: '3'

volumes:
  mariadb_volume: {}
  wordpress_volume: {}
services:
  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - intra
    environment:
      - USER=${MARIADB_USER}
    depends_on:
      - wordpress
  wordpress:
    build: ./wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASS=${MARIADB_PASS}
      - MARIADB_NAME=${MARIADB_NAME}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
      - WORDPRESS_USER_LOGIN=${WORDPRESS_USER_LOGIN}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL}
      - WORDPRESS_USER_PASS=${WORDPRESS_USER_PASS}
    depends_on:
      - mariadb
networks:
  intra:
    driver: bridge
# volumes:
#   mariadb_volume:
#     name: mariadb_volume
#     driver: local
#     driver_opts:
#       o: bind
#       type: volume
#       device: ${VOLUME_PATH}/mariadb
#   wordpress_volume:
#     name: wordpress_volume
#     driver: local
#     driver_opts:
#       o: bind
#       type: volume
#       device: ${VOLUME_PATH}/wordpress

