version: '3'

volumes:
  mariadb_volume: {}
  wordpress_volume: {}
services:
  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - intra
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - intra
  wordpress:
    build: ./wordpress
    restart: always
    volumes:
      - wordpress_volume:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASS=${MARIADB_PASS}
      - MARIADB_NAME=${MARIADB_NAME}
networks:
  intra:
    driver: bridge

