version: '3'

volumes:
  data: {}
services:
  mariadb:
    build: ./mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - intra
    tty: true # 결국 bash 처럼 빼줘야할듯
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - intra
    tty: true # 결국 bash 처럼 빼줘야할듯
  wordpress:
    build: ./wordpress
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASS=${MARIADB_PASS}
      - MARIADB_NAME=${MARIADB_NAME}
    tty: true # 결국 bash 처럼 빼줘야할듯
networks:
  intra:
    driver: bridge

