version: '3'

volumes:
  data: {}
services:
  mariadb:
    build: ./mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - intra
    env_file:
      - .env
    tty: true
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - data:/var/www/html
    networks:
      - intra
    env_file:
      - .env
    tty: true
  wordpress:
    build: ./wordpress
    restart: always
    volumes:
      - data:/var/www/html
    expose:
      - "9000"
    networks:
      - intra
    env_file:
      - .env
    tty: true
networks:
  intra:
    driver: bridge

